In [1]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [2]:
import src.data_io as data
import src.analysis as analyzer
from src.config import load_config, update_config

In [3]:
config = load_config()
data_path = f"{config['paths']['processed_data']}/{config['files']['processed_dataset']}"

In [4]:
df = data.load_dataset(f'{data_path}.csv')
df = df[df['year'] != 2026]

In [5]:
df.head()

,year,month,country,student_ai_usage_pct,teacher_ai_usage_pct,schools_ai_adoption_pct,avg_daily_ai_usage_min,top_ai_tool,internet_penetration_pct,education_index,government_ai_policy,urban_ai_usage_pct,rural_ai_usage_pct,ai_in_curriculum,gender_gap_ai_usage_pct
0,2015,January,US,1,2,1,19,Google Gemini,90,0.90,Unknown,1,0,Yes,6
1,2015,January,UK,4,1,5,11,Google Gemini,92,0.91,Draft,7,0,Yes,5
2,2015,January,China,6,5,4,7,ChatGPT,70,0.75,Active,8,1,No,7
3,2015,January,India,7,5,0,59,Microsoft Copilot,50,0.64,Unknown,10,0,Yes,7
4,2015,January,Germany,9,7,6,29,Khanmigo,93,0.94,Active,13,0,Yes,1

### How does AI tool preference evolve over time?

In [6]:
counts = analyzer.count_distribution(df, 'year', 'top_ai_tool', pct=True)
counts

top_ai_tool   ChatGPT  Google Gemini  Khanmigo  Microsoft Copilot
year
2015         0.216667       0.275000  0.216667           0.291667
2016         0.333333       0.233333  0.233333           0.200000
2017         0.291667       0.191667  0.266667           0.250000
2018         0.241667       0.216667  0.275000           0.266667
2019         0.233333       0.208333  0.325000           0.233333
2020         0.250000       0.233333  0.250000           0.266667
2021         0.208333       0.283333  0.216667           0.291667
2022         0.258333       0.283333  0.216667           0.241667
2023         0.258333       0.283333  0.233333           0.225000
2024         0.316667       0.233333  0.208333           0.241667
2025         0.283333       0.258333  0.216667           0.241667

In [7]:
save_path = f'{config['paths']['interim_data']}/insights/AI Tool Preference by Year'
data.save_dataset(counts, f'{save_path}.csv', index=True)

In [8]:
update_config('files', 'tool_preference_year', 'insights/AI Tool Preference by Year')

Updated [files] -> tool_preference_year: insights/AI Tool Preference by Year

### How does AI tool preference vary across countries?

In [9]:
counts = analyzer.count_distribution(df, 'country', 'top_ai_tool', pct=True)
counts

top_ai_tool   ChatGPT  Google Gemini  Khanmigo  Microsoft Copilot
country
Australia    0.265152       0.227273  0.295455           0.212121
Brazil       0.272727       0.242424  0.234848           0.250000
Canada       0.219697       0.257576  0.272727           0.250000
China        0.250000       0.250000  0.242424           0.257576
Germany      0.318182       0.265152  0.151515           0.265152
India        0.295455       0.212121  0.189394           0.303030
Nigeria      0.219697       0.242424  0.242424           0.295455
Pakistan     0.272727       0.227273  0.272727           0.227273
UK           0.257576       0.265152  0.265152           0.212121
US           0.257576       0.265152  0.250000           0.227273

In [10]:
save_path = f'{config['paths']['interim_data']}/insights/AI Tool Preference by Country'
data.save_dataset(counts, f'{save_path}.csv', index=True)

In [11]:
update_config('files', 'tool_preference_country', 'insights/AI Tool Preference by Country')

Updated [files] -> tool_preference_country: insights/AI Tool Preference by Country

AI tool preferences vary within a relatively narrow range across both years and countries, with no strong temporal or geographic differentiation.

### How does AI usage evolve over time across different user groups?

In [12]:
aggregate = analyzer.aggregate_metric(df, 'year', ['urban_ai_usage_pct','rural_ai_usage_pct','student_ai_usage_pct','teacher_ai_usage_pct','schools_ai_adoption_pct','gender_gap_ai_usage_pct'])
aggregate

,urban_ai_usage_pct,rural_ai_usage_pct,student_ai_usage_pct,teacher_ai_usage_pct,schools_ai_adoption_pct,gender_gap_ai_usage_pct
year,,,,,,
2015,7.833333,0.158333,4.983333,4.041667,3.375000,5.208333
2016,13.033333,2.133333,10.408333,9.225000,8.633333,5.458333
2017,18.075000,5.291667,15.400000,14.008333,13.466667,5.108333
2018,21.741667,9.058333,19.316667,19.458333,18.358333,5.391667
2019,28.150000,15.225000,25.466667,23.741667,23.633333,5.908333
2020,32.383333,20.100000,30.033333,29.325000,28.450000,5.341667
2021,37.625000,25.058333,35.300000,34.258333,33.516667,5.191667
2022,42.500000,29.608333,39.950000,38.583333,38.475000,5.758333
2023,47.458333,35.691667,44.841667,44.108333,43.541667,5.591667
2024,52.483333,40.000000,49.900000,49.083333,48.683333,5.641667
2025,57.900000,45.625000,55.333333,53.450000,53.425000,5.050000

In [13]:
save_path = f'{config['paths']['interim_data']}/plotting/Yearly AI Usage Summary'
data.save_dataset(aggregate, f'{save_path}.csv', index=True)

In [14]:
update_config('files', 'ai_usage_yearly', 'plotting/Yearly AI Usage Summary')

Updated [files] -> ai_usage_yearly: plotting/Yearly AI Usage Summary

Most AI usage metrics show substantial variation over time. In contrast, gender gap in AI usage remains comparatively stable within a narrow range. School-level AI adoption also exhibits noticeable temporal variation, suggesting that institutional adoption changes meaningfully across years.

### How do countries compare in terms of internet penetration and education index?

In [15]:
analyzer.summary_metrics(df, 'country', ['internet_penetration_pct', 'education_index'])

          internet_penetration_pct                      education_index        \
                             count  mean median min max           count  mean
country
Australia                      132  96.0   96.0  96  96             132  0.93
Brazil                         132  75.0   75.0  75  75             132  0.70
Canada                         132  94.0   94.0  94  94             132  0.92
China                          132  70.0   70.0  70  70             132  0.75
Germany                        132  93.0   93.0  93  93             132  0.94
India                          132  50.0   50.0  50  50             132  0.64
Nigeria                        132  42.0   42.0  42  42             132  0.52
Pakistan                       132  45.0   45.0  45  45             132  0.55
UK                             132  92.0   92.0  92  92             132  0.91
US                             132  90.0   90.0  90  90             132  0.90


          median   min   max
country
Australia   0.93  0.93  0.93
Brazil      0.70  0.70  0.70
Canada      0.92  0.92  0.92
China       0.75  0.75  0.75
Germany     0.94  0.94  0.94
India       0.64  0.64  0.64
Nigeria     0.52  0.52  0.52
Pakistan    0.55  0.55  0.55
UK          0.91  0.91  0.91
US          0.90  0.90  0.90

In [16]:
aggregate = analyzer.aggregate_metric(df, 'country', ['internet_penetration_pct', 'education_index'])
aggregate

           internet_penetration_pct  education_index
country
Australia                      96.0             0.93
Brazil                         75.0             0.70
Canada                         94.0             0.92
China                          70.0             0.75
Germany                        93.0             0.94
India                          50.0             0.64
Nigeria                        42.0             0.52
Pakistan                       45.0             0.55
UK                             92.0             0.91
US                             90.0             0.90

In [17]:
save_path = f'{config['paths']['interim_data']}/plotting/Country wise Structural Summary'
data.save_dataset(aggregate, f'{save_path}.csv', index=True)

In [18]:
update_config('files', 'structural_summary_country', 'plotting/Country wise Structural Summary')

Updated [files] -> structural_summary_country: plotting/Country wise Structural Summary

Internet penetration and education index are fixed country-level structural indicators in this analysis. While they do not vary within a country, cross-country comparison suggests a broadly positive association between them. Visualization may provide clearer insight into the strength and pattern of this relationship.

### How does internet penetration relate to AI usage patterns?

In [19]:
df['urban_rural_ai_usage_pct_gap'] = df['urban_ai_usage_pct'] - df['rural_ai_usage_pct']

In [20]:
analyzer.summary_metrics(df, ['country','internet_penetration_pct'], ['urban_rural_ai_usage_pct_gap', 'gender_gap_ai_usage_pct', 'avg_daily_ai_usage_min'])

                                   urban_rural_ai_usage_pct_gap             \
                                                          count       mean
country   internet_penetration_pct
Australia 96                                                132  11.840909
Brazil    75                                                132  11.803030
Canada    94                                                132  12.250000
China     70                                                132  12.128788
Germany   93                                                132  12.068182
India     50                                                132  11.537879
Nigeria   42                                                132  12.000000
Pakistan  45                                                132  12.212121
UK        92                                                132  11.621212
US        90                                                132  11.840909

                                                  gender_gap_ai_usage_pct  \
                                   median min max                   count
country   internet_penetration_pct
Australia 96                         12.0   2  19                     132
Brazil    75                         12.0   1  20                     132
Canada    94                         12.5   5  20                     132
China     70                         12.0   2  20                     132
Germany   93                         12.0   1  20                     132
India     50                         11.0   2  20                     132
Nigeria   42                         11.5   1  20                     132
Pakistan  45                         12.0   0  20                     132
UK        92                         11.5   0  20                     132
US        90                         12.0   1  20                     132

                                                             \
                                        mean median min max
country   internet_penetration_pct
Australia 96                        5.174242    5.0   1  10
Brazil    75                        5.136364    5.0   1  10
Canada    94                        5.704545    6.0   1  10
China     70                        5.803030    6.0   1  10
Germany   93                        5.287879    5.0   1  10
India     50                        5.500000    5.0   1  10
Nigeria   42                        5.060606    5.0   1  10
Pakistan  45                        5.727273    6.0   1  10
UK        92                        5.166667    5.0   1  10
US        90                        5.666667    6.0   1  10

                                   avg_daily_ai_usage_min                    \
                                                    count       mean median
country   internet_penetration_pct
Australia 96                                          132  34.810606   35.0
Brazil    75                                          132  30.060606   27.5
Canada    94                                          132  35.424242   36.0
China     70                                          132  33.060606   34.0
Germany   93                                          132  31.803030   31.0
India     50                                          132  32.515152   32.0
Nigeria   42                                          132  33.643939   33.5
Pakistan  45                                          132  33.462121   33.0
UK        92                                          132  32.583333   32.0
US        90                                          132  30.325758   31.5


                                   min max
country   internet_penetration_pct
Australia 96                         5  60
Brazil    75                         5  60
Canada    94                         5  60
China     70                         6  60
Germany   93                         5  60
India     50                         5  60
Nigeria   42                         5  60
Pakistan  45                         6  60
UK        92                         5  60
US        90                         5  60

Cross-country comparison shows that gender gap and average daily AI usage remain within a similar range across countries. Urban–rural usage differences also vary within a relatively narrow range. However, changes in country-level mean and median values across years indicate temporal variation within countries.

### How does education index relate to AI adoption in educational systems?

In [21]:
analyzer.summary_metrics(df, ['country','education_index'], ['student_ai_usage_pct', 'teacher_ai_usage_pct', 'schools_ai_adoption_pct'])

                          student_ai_usage_pct                            \
                                         count       mean median min max
country   education_index
Australia 0.93                             132  30.106061   30.0   0  60
Brazil    0.70                             132  29.712121   29.0   0  60
Canada    0.92                             132  30.159091   31.0   3  60
China     0.75                             132  29.931818   30.0   0  60
Germany   0.94                             132  29.750000   30.0   1  60
India     0.64                             132  30.212121   30.0   0  60
Nigeria   0.52                             132  30.015152   29.5   0  60
Pakistan  0.55                             132  30.136364   30.5   0  59
UK        0.91                             132  30.098485   29.5   0  60
US        0.90                             132  30.727273   31.0   0  60

                          teacher_ai_usage_pct                            \
                                         count       mean median min max
country   education_index
Australia 0.93                             132  28.909091   29.0   0  57
Brazil    0.70                             132  28.909091   28.0   1  58
Canada    0.92                             132  29.068182   30.0   1  57
China     0.75                             132  28.931818   28.5   0  56
Germany   0.94                             132  29.348485   28.0   1  57
India     0.64                             132  29.007576   31.0   2  58
Nigeria   0.52                             132  28.666667   29.0   0  57
Pakistan  0.55                             132  29.348485   28.0   0  58
UK        0.91                             132  28.946970   28.5   0  57
US        0.90                             132  29.121212   29.5   0  58

                          schools_ai_adoption_pct
                                            count       mean median min max
country   education_index
Australia 0.93                                132  28.727273   28.0   0  57
Brazil    0.70                                132  28.492424   28.0   0  57
Canada    0.92                                132  28.666667   28.0   0  55
China     0.75                                132  28.022727   27.5   0  57
Germany   0.94                                132  28.931818   29.0   0  57
India     0.64                                132  28.212121   29.0   0  57
Nigeria   0.52                                132  28.643939   28.5   0  57
Pakistan  0.55                                132  28.734848   29.0   0  57
UK        0.91                                132  28.333333   27.5   0  57
US        0.90                                132  28.287879   29.0   0  57

Cross-country comparison shows that AI usage and adoption metrics vary within a similar range across countries. However, changes in country-level mean and median values across years indicate temporal variation within countries.